#!/bin/bash
# Pre-commit global hook to run a notebook cleanup script

# Get repo root
REPO_ROOT=$(git rev-parse --show-toplevel)

# Run local pre-commit hook, if it exists
if [ -e $REPO_ROOT/.git/hooks/pre-commit ]; then
    if ! ($REPO_ROOT/.git/hooks/pre-commit "$@"); then
        exit 1;
    fi
fi

# Apply notebook clean up script
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
for FILE in $STAGED_FILES; do
    if [[ "$FILE" == *.ipynb ]]; then
        # Run notebook cleanup script
        python3 $HOME/.jupyter/clean_notebook.py "$REPO_ROOT/$FILE"
        # Re-stage file if the script modifies it
        git add "$FILE"
    fi
done
