name: Check jupyter metadata
description: Check for stray outputs, counts and metadata in ipynb files

inputs:
  pattern:
    description: Search pattern
    required: true
  expect-failure:
    description: Should the metadata check fail or not
    required: false
    default: false


runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        pip3 -q install -r ${GITHUB_ACTION_PATH}/scripts/requirements.txt
      shell: bash
    - name: Check for stray outputs, counts and metadata in ipynb files
      run: |
        python3 ${GITHUB_ACTION_PATH}/scripts/check_metadata.py "${{ inputs.pattern }}" "${{ inputs.expect-failure }}"
      shell: bash
