name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip -q install -r scripts/requirements.txt -r tests/requirements.txt
      - name: Run flake8
        run: |
          python3 -m flake8 .
      - name: Run isort
        run: |
          python3 -m isort --check --diff .
      - name: Run mypy
        run: |
          python3 -m mypy .
      - name: Run yamllint
        run: |
          python3 -m yamllint -d "{extends: default, rules: {document-start: {present: false}, line-length: disable, truthy: {check-keys: false}}}" .
      - name: Run tests
        run: |
          python3 -m pytest tests
      - name: Run action on successful test files
        uses: ./
        with:
          pattern: tests/data/success/*.ipynb
      - name: Run action on failing test files
        uses: ./
        with:
          pattern: tests/data/fail/*.ipynb
          expect-failure: true

  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'RBniCS/check-jupyter-metadata-action' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci.yml
          days-elapsed: 50
